[general]
logdir = "/var/log/burrow"
logconfig = "/etc/burrow/logging.cfg"
pidfile = "/var/run/burrow.pid"

[zookeeper]
servers = ["zookeeper:2181"]
timeout = 10
rootpath = "/burrow"

[kafka]
cluster = "local"
servers = ["bootstraps:9092"]
topic_refresh = 60
offset_refresh = 30