version: "3.7"

services:
  # grafana:

  ## ui for apache kafka
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED="true"
      - KAFKA_CLUSTERS_0_NAME=devstg-msk
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=bootstraps:9092
    volumes:
      - ./ui-config.yml:/etc/kafkaui/dynamic_config.yml
    
  ## burrow
  # burrow:
  #   container_name: monitor_consumer_lag
  #   image: ghcr.io/linkedin/burrow/burrow:v1.8.0
  #   volumes:
  #     - ./burrow-config:/etc/burrow
  #   environment:
  #     - BURROW_LOGLEVEL=info
  #   ports:
  #     - 8000:8000
    
    
  